version: '3'

services:
    nginx:
        container_name: nginx
        build: ./
        restart: always
        volumes:
          - ./html:/usr/share/nginx/html
        ports:
          - 8080:80
