version: "3.9"
services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command:
      - start.sh
      - immich
    container_name: Immich-SERVER
    hostname: immich-server
    env_file:
      - immich.env
    ports:
      - 2283:3001
    volumes:
      - ./upload:/usr/src/app/upload
    restart: always
    depends_on:
      - immich-redis
      - immich-db
      
  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command:
      - start.sh
      - microservices
    container_name: Immich-MICROSERVICES
    hostname: immich-microservices
    env_file:
      - immich.env
    volumes:
      - ./upload:/usr/src/app/upload
      - ./micro:/usr/src/app/.reverse-geocoding-dump
    restart: always
    depends_on:
      - immich-redis
      - immich-db
      
  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    env_file:
      - immich.env
    volumes:
      - ./upload:/usr/src/app/upload
      - ./cache:/cache
    restart: always
    depends_on:
      - immich-db
      
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./redis:/data
    restart: always
    
  immich-db:
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: Immich-DB
    hostname: immich-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
