version: "3.9"
services:
  immich-redis:
    image: redis
    container_name: Immich-REDIS
    hostname: immich-redis
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./redis:/data
    restart: always

  immich-db:
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce231
    container_name: Immich-DB
    hostname: immich-db
    env_file:
      - immich.env
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-server.sh"]
    container_name: Immich-SERVER
    hostname: immich-server
    env_file:
      - immich.env
    ports:
      - 2283:3001
    volumes:
      - ./upload:/usr/src/app/upload
    restart: always
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:release
    command: ["start-microservices.sh"]
    container_name: Immich-MICROSERVICES
    hostname: immich-microservices
    env_file:
      - immich.env
    volumes:
      - ./upload:/usr/src/app/upload
      - ./micro:/usr/src/app/.reverse-geocoding-dump
    restart: always
    depends_on:
      immich-redis:
        condition: service_healthy
      immich-db:
        condition: service_started

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    env_file:
      - immich.env
    volumes:
      - ./upload:/usr/src/app/upload
      - ./cache:/cache
    restart: always
    depends_on:
      immich-db:
        condition: service_started
